export const LOAD_LOCALITIES = 'LOAD_LOCALITIES'
export const SELECT_LOCATION = 'SELECT_LOCATION'
export const LOAD_SOCKET_RESPONSE = 'LOAD_SOCKET_RESPONSE'
/*
export const REFRESH_COUNTER = 'REFRESH_COUNTER'
export const ADD_COUNTER = 'ADD_COUNTER'
export const TOGGLE_HEADER = 'TOGGLE_HEADER'
export const DELETE_COUNTER = 'DELETE_COUNTER'
export const SET_FILTER = 'SET_FILTER'*/